/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.auth.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 登录请求
 *
 * @param email 邮箱
 * @param loginType 登录方式: EMAIL_CODE-验证码登录, EMAIL_PASSWORD-密码登录
 * @param code 验证码(验证码登录时必填)
 * @param password 密码(密码登录时必填)
 */
@Serializable

data class LoginRequest (

    /* 邮箱 */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* 登录方式: EMAIL_CODE-验证码登录, EMAIL_PASSWORD-密码登录 */
    @SerialName(value = "loginType")
    val loginType: kotlin.String,

    /* 验证码(验证码登录时必填) */
    @SerialName(value = "code")
    val code: kotlin.String? = null,

    /* 密码(密码登录时必填) */
    @SerialName(value = "password")
    val password: kotlin.String? = null

)

