/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.auth.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 登录响应
 *
 * @param userId 用户ID
 * @param username 用户名
 * @param email 邮箱
 * @param token Token
 */
@Serializable

data class LoginResponse (

    /* 用户ID */
    @SerialName(value = "userId")
    val userId: kotlin.Long? = null,

    /* 用户名 */
    @SerialName(value = "username")
    val username: kotlin.String? = null,

    /* 邮箱 */
    @SerialName(value = "email")
    val email: kotlin.String? = null,

    /* Token */
    @SerialName(value = "token")
    val token: kotlin.String? = null

)

