/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.auth.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 注册请求
 *
 * @param email 邮箱
 * @param code 验证码
 * @param username 用户名
 * @param password 密码
 */
@Serializable

data class RegisterRequest (

    /* 邮箱 */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* 验证码 */
    @SerialName(value = "code")
    val code: kotlin.String,

    /* 用户名 */
    @SerialName(value = "username")
    val username: kotlin.String,

    /* 密码 */
    @SerialName(value = "password")
    val password: kotlin.String

)

