/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.auth.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 发送验证码请求
 *
 * @param email 邮箱
 * @param type 验证码类型: LOGIN-登录, REGISTER-注册
 */
@Serializable

data class SendCodeRequest (

    /* 邮箱 */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* 验证码类型: LOGIN-登录, REGISTER-注册 */
    @SerialName(value = "type")
    val type: kotlin.String

)

