/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.auth.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 用户信息响应
 *
 * @param userId 用户ID
 * @param username 用户名
 * @param email 邮箱
 * @param avatar 头像
 * @param status 状态: 0-禁用, 1-正常
 * @param createTime 创建时间
 */
@Serializable

data class UserInfoResponse (

    /* 用户ID */
    @SerialName(value = "userId")
    val userId: kotlin.Long? = null,

    /* 用户名 */
    @SerialName(value = "username")
    val username: kotlin.String? = null,

    /* 邮箱 */
    @SerialName(value = "email")
    val email: kotlin.String? = null,

    /* 头像 */
    @SerialName(value = "avatar")
    val avatar: kotlin.String? = null,

    /* 状态: 0-禁用, 1-正常 */
    @SerialName(value = "status")
    val status: kotlin.Int? = null,

    /* 创建时间 */
    @Contextual @SerialName(value = "createTime")
    val createTime: java.time.OffsetDateTime? = null

)

