/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ID映射
 *
 * @param localId 本地日程ID
 * @param cloudId 云端日程ID
 * @param action 操作类型
 */
@Serializable

data class IdMapping (

    /* 本地日程ID */
    @SerialName(value = "localId")
    val localId: kotlin.Long? = null,

    /* 云端日程ID */
    @SerialName(value = "cloudId")
    val cloudId: kotlin.Long? = null,

    /* 操作类型 */
    @SerialName(value = "action")
    val action: kotlin.String? = null

)

