/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 查询日程请求
 *
 * @param queryType 查询类型
 * @param userId 
 * @param startDate 开始日期（时间戳，仅在queryType为range时需要）
 * @param endDate 结束日期（时间戳，仅在queryType为range时需要）
 */
@Serializable

data class QueryScheduleRequest (

    /* 查询类型 */
    @SerialName(value = "queryType")
    val queryType: QueryScheduleRequest.QueryType,

    @SerialName(value = "userId")
    val userId: kotlin.String? = null,

    /* 开始日期（时间戳，仅在queryType为range时需要） */
    @SerialName(value = "startDate")
    val startDate: kotlin.Long? = null,

    /* 结束日期（时间戳，仅在queryType为range时需要） */
    @SerialName(value = "endDate")
    val endDate: kotlin.Long? = null

) {

    /**
     * 查询类型
     *
     * Values: ALL,UNCOMPLETED,COMPLETED,RANGE
     */
    @Serializable
    enum class QueryType(val value: kotlin.String) {
        @SerialName(value = "ALL") ALL("ALL"),
        @SerialName(value = "UNCOMPLETED") UNCOMPLETED("UNCOMPLETED"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "RANGE") RANGE("RANGE");
    }
}

