/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model

import cn.szu.blankxiao.mycalendar.remote.calendar.model.SyncScheduleResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param success 
 * @param code 
 * @param info 
 * @param `data` 
 */
@Serializable

data class ResultSyncScheduleResponse (

    @SerialName(value = "success")
    val success: kotlin.Boolean? = null,

    @SerialName(value = "code")
    val code: kotlin.Int? = null,

    @SerialName(value = "info")
    val info: kotlin.String? = null,

    @SerialName(value = "data")
    val `data`: SyncScheduleResponse? = null

)

