/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model

import cn.szu.blankxiao.mycalendar.remote.calendar.model.IdMapping
import cn.szu.blankxiao.mycalendar.remote.calendar.model.ScheduleResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 同步日程响应
 *
 * @param createdCount 新创建的日程数量
 * @param updatedCount 更新的日程数量
 * @param skippedCount 跳过的日程数量
 * @param idMappings 本地ID到云端ID的映射
 * @param allSchedules 同步后的所有日程数据
 */
@Serializable

data class SyncScheduleResponse (

    /* 新创建的日程数量 */
    @SerialName(value = "createdCount")
    val createdCount: kotlin.Int? = null,

    /* 更新的日程数量 */
    @SerialName(value = "updatedCount")
    val updatedCount: kotlin.Int? = null,

    /* 跳过的日程数量 */
    @SerialName(value = "skippedCount")
    val skippedCount: kotlin.Int? = null,

    /* 本地ID到云端ID的映射 */
    @SerialName(value = "idMappings")
    val idMappings: kotlin.collections.List<IdMapping>? = null,

    /* 同步后的所有日程数据 */
    @SerialName(value = "allSchedules")
    val allSchedules: kotlin.collections.List<ScheduleResponse>? = null

)

