/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 同步日程项
 *
 * @param title 日程标题
 * @param scheduleDate 日程日期（时间戳）
 * @param localId 本地日程ID
 * @param description 日程描述
 * @param isChecked 是否已完成
 * @param reminderEnabled 是否启用提醒
 * @param reminderTime 提醒时间戳
 * @param createdAt 创建时间戳
 * @param updatedAt 更新时间戳
 */
@Serializable

data class SyncScheduleItem (

    /* 日程标题 */
    @SerialName(value = "title")
    val title: kotlin.String,

    /* 日程日期（时间戳） */
    @SerialName(value = "scheduleDate")
    val scheduleDate: kotlin.Long,

    /* 本地日程ID */
    @SerialName(value = "localId")
    val localId: kotlin.Long? = null,

    /* 日程描述 */
    @SerialName(value = "description")
    val description: kotlin.String? = null,

    /* 是否已完成 */
    @SerialName(value = "isChecked")
    val isChecked: kotlin.Boolean? = null,

    /* 是否启用提醒 */
    @SerialName(value = "reminderEnabled")
    val reminderEnabled: kotlin.Boolean? = null,

    /* 提醒时间戳 */
    @SerialName(value = "reminderTime")
    val reminderTime: kotlin.Long? = null,

    /* 创建时间戳 */
    @SerialName(value = "createdAt")
    val createdAt: kotlin.Long? = null,

    /* 更新时间戳 */
    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.Long? = null

)

