/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model

import cn.szu.blankxiao.mycalendar.remote.calendar.model.SyncScheduleItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 同步日程请求
 *
 * @param schedules 待同步的日程列表
 * @param syncMode 同步模式: MERGE-合并, LOCAL_FIRST-本地优先, CLOUD_FIRST-云端优先
 */
@Serializable

data class SyncScheduleRequest (

    /* 待同步的日程列表 */
    @SerialName(value = "schedules")
    val schedules: kotlin.collections.List<SyncScheduleItem>,

    /* 同步模式: MERGE-合并, LOCAL_FIRST-本地优先, CLOUD_FIRST-云端优先 */
    @SerialName(value = "syncMode")
    val syncMode: kotlin.String? = "MERGE"

)

