/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * ID鏄犲皠
 *
 * @param localId 鏈湴鏃ョ▼ID
 * @param cloudId 浜戠鏃ョ▼ID
 * @param action 鎿嶄綔绫诲瀷
 */
@Serializable

data class IdMapping (

    /* 鏈湴鏃ョ▼ID */
    @SerialName(value = "localId")
    val localId: kotlin.Long? = null,

    /* 浜戠鏃ョ▼ID */
    @SerialName(value = "cloudId")
    val cloudId: kotlin.Long? = null,

    /* 鎿嶄綔绫诲瀷 */
    @SerialName(value = "action")
    val action: kotlin.String? = null

)

