/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 鏌ヨ鏃ョ▼璇锋眰
 *
 * @param queryType 鏌ヨ绫诲瀷
 * @param userId 
 * @param startDate 寮€濮嬫棩鏈燂紙鏃堕棿鎴筹紝浠呭湪queryType涓簉ange鏃堕渶瑕侊級
 * @param endDate 缁撴潫鏃ユ湡锛堟椂闂存埑锛屼粎鍦╭ueryType涓簉ange鏃堕渶瑕侊級
 */
@Serializable

data class QueryScheduleRequest (

    /* 鏌ヨ绫诲瀷 */
    @SerialName(value = "queryType")
    val queryType: QueryScheduleRequest.QueryType,

    @SerialName(value = "userId")
    val userId: kotlin.String? = null,

    /* 寮€濮嬫棩鏈燂紙鏃堕棿鎴筹紝浠呭湪queryType涓簉ange鏃堕渶瑕侊級 */
    @SerialName(value = "startDate")
    val startDate: kotlin.Long? = null,

    /* 缁撴潫鏃ユ湡锛堟椂闂存埑锛屼粎鍦╭ueryType涓簉ange鏃堕渶瑕侊級 */
    @SerialName(value = "endDate")
    val endDate: kotlin.Long? = null

) {

    /**
     * 鏌ヨ绫诲瀷
     *
     * Values: ALL,UNCOMPLETED,COMPLETED,RANGE
     */
    @Serializable
    enum class QueryType(val value: kotlin.String) {
        @SerialName(value = "ALL") ALL("ALL"),
        @SerialName(value = "UNCOMPLETED") UNCOMPLETED("UNCOMPLETED"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "RANGE") RANGE("RANGE");
    }
}

