/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 鍚屾鍚庣殑鎵€鏈夋棩绋嬫暟鎹?
 *
 * @param id 
 * @param userId 
 * @param title 
 * @param description 
 * @param scheduleDate 
 * @param isChecked 
 * @param reminderEnabled 
 * @param reminderTime 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class ScheduleResponse (

    @SerialName(value = "id")
    val id: kotlin.Long? = null,

    @SerialName(value = "userId")
    val userId: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "scheduleDate")
    val scheduleDate: kotlin.Long? = null,

    @SerialName(value = "isChecked")
    val isChecked: kotlin.Boolean? = null,

    @SerialName(value = "reminderEnabled")
    val reminderEnabled: kotlin.Boolean? = null,

    @SerialName(value = "reminderTime")
    val reminderTime: kotlin.Long? = null,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.Long? = null,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.Long? = null

)

