/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model

import cn.szu.blankxiao.mycalendar.remote.calendar.model.IdMapping
import cn.szu.blankxiao.mycalendar.remote.calendar.model.ScheduleResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 鍚屾鏃ョ▼鍝嶅簲
 *
 * @param createdCount 鏂板垱寤虹殑鏃ョ▼鏁伴噺
 * @param updatedCount 鏇存柊鐨勬棩绋嬫暟閲?
 * @param skippedCount 璺宠繃鐨勬棩绋嬫暟閲?
 * @param idMappings 鏈湴ID鍒颁簯绔疘D鐨勬槧灏?
 * @param allSchedules 鍚屾鍚庣殑鎵€鏈夋棩绋嬫暟鎹?
 */
@Serializable

data class SyncScheduleResponse (

    /* 鏂板垱寤虹殑鏃ョ▼鏁伴噺 */
    @SerialName(value = "createdCount")
    val createdCount: kotlin.Int? = null,

    /* 鏇存柊鐨勬棩绋嬫暟閲?*/
    @SerialName(value = "updatedCount")
    val updatedCount: kotlin.Int? = null,

    /* 璺宠繃鐨勬棩绋嬫暟閲?*/
    @SerialName(value = "skippedCount")
    val skippedCount: kotlin.Int? = null,

    /* 鏈湴ID鍒颁簯绔疘D鐨勬槧灏?*/
    @SerialName(value = "idMappings")
    val idMappings: kotlin.collections.List<IdMapping>? = null,

    /* 鍚屾鍚庣殑鎵€鏈夋棩绋嬫暟鎹?*/
    @SerialName(value = "allSchedules")
    val allSchedules: kotlin.collections.List<ScheduleResponse>? = null

)

