/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 鍚屾鏃ョ▼椤?
 *
 * @param title 鏃ョ▼鏍囬
 * @param scheduleDate 鏃ョ▼鏃ユ湡锛堟椂闂存埑锛?
 * @param localId 鏈湴鏃ョ▼ID
 * @param description 鏃ョ▼鎻忚堪
 * @param isChecked 鏄惁宸插畬鎴?
 * @param reminderEnabled 鏄惁鍚敤鎻愰啋
 * @param reminderTime 鎻愰啋鏃堕棿鎴?
 * @param createdAt 鍒涘缓鏃堕棿鎴?
 * @param updatedAt 鏇存柊鏃堕棿鎴?
 */
@Serializable

data class SyncScheduleItem (

    /* 鏃ョ▼鏍囬 */
    @SerialName(value = "title")
    val title: kotlin.String,

    /* 鏃ョ▼鏃ユ湡锛堟椂闂存埑锛?*/
    @SerialName(value = "scheduleDate")
    val scheduleDate: kotlin.Long,

    /* 鏈湴鏃ョ▼ID */
    @SerialName(value = "localId")
    val localId: kotlin.Long? = null,

    /* 鏃ョ▼鎻忚堪 */
    @SerialName(value = "description")
    val description: kotlin.String? = null,

    /* 鏄惁宸插畬鎴?*/
    @SerialName(value = "isChecked")
    val isChecked: kotlin.Boolean? = null,

    /* 鏄惁鍚敤鎻愰啋 */
    @SerialName(value = "reminderEnabled")
    val reminderEnabled: kotlin.Boolean? = null,

    /* 鎻愰啋鏃堕棿鎴?*/
    @SerialName(value = "reminderTime")
    val reminderTime: kotlin.Long? = null,

    /* 鍒涘缓鏃堕棿鎴?*/
    @SerialName(value = "createdAt")
    val createdAt: kotlin.Long? = null,

    /* 鏇存柊鏃堕棿鎴?*/
    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.Long? = null

)

