/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.szu.blankxiao.mycalendar.remote.calendar.model

import cn.szu.blankxiao.mycalendar.remote.calendar.model.SyncScheduleItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 鍚屾鏃ョ▼璇锋眰
 *
 * @param schedules 寰呭悓姝ョ殑鏃ョ▼鍒楄〃
 * @param syncMode 鍚屾妯″紡: MERGE-鍚堝苟, LOCAL_FIRST-鏈湴浼樺厛, CLOUD_FIRST-浜戠浼樺厛
 */
@Serializable

data class SyncScheduleRequest (

    /* 寰呭悓姝ョ殑鏃ョ▼鍒楄〃 */
    @SerialName(value = "schedules")
    val schedules: kotlin.collections.List<SyncScheduleItem>,

    /* 鍚屾妯″紡: MERGE-鍚堝苟, LOCAL_FIRST-鏈湴浼樺厛, CLOUD_FIRST-浜戠浼樺厛 */
    @SerialName(value = "syncMode")
    val syncMode: kotlin.String? = "MERGE"

)

